<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE >
<html data-ng-app="ngModule" ng-cloak>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Pharmacy Bill</title>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" />
<%@ include file="../Common/includeScript.jsp" %>
  <script src="resources/js/Pharmacy/pharmacyController.js" ></script> 
<script type="text/javascript">

</script>
</head>
<body ng-controller="pharmacyCtrl">
  <%@ include file="../Common/menubar.jsp" %>
    <%@ include file="../Common/sidebar.jsp" %>
 
    <div class="clear">
        <div class="right_block">
        
         <h1 class="heading">Pharmacy bill</h1>
         
         <div class="container">
         
         <div>
            
            <div class="row">
            
            <div class="form-group col-md-2" >
				    <label>Patient:</label>
				     <select ng-model="bill.patientId" class="form-control">
				        <option ng-repeat="patient in listpatientdata" value="{{patient.patientId}}">{{patient.patientName}}</option>
				     </select>	
				     <br>			    
				    <input type="text" name="" ng-model="bill.patientId" class="form-control" >
				  </div>
				  
				  
				  <div class="form-group col-md-2" >
				    <label>Doctor:</label>
				     <select ng-model="bill.doctorId" class="form-control">
				        <option ng-repeat="doctor in listdoctorsdata" value="{{doctor.doctorId}}">{{doctor.doctorName}}</option>
				     </select>
				      <br>					    
				    <input type="text" name="" ng-model="bill.doctorId" class="form-control" >
				  </div>
				  
				  <div class="form-group col-md-2" >
				    <label>Prepared By:</label>
				     <select ng-model="bill.staffId" class="form-control">
				        <option ng-repeat="staff in liststaffdata" value="{{staff.staffId}}">{{staff.staffName}}</option>
				     </select>	
				      <br>				    
				    <input type="text" name="" ng-model="bill.staffId" class="form-control" >
				  </div>
            
            
            
            
				  <!-- <div class="form-group col-md-3">
				    <label>Patient Name</label>
				     <input type="text"   data-ng-model="bill.patientId" class="form-control" placeholder="Patient Name">				  
				  </div>
				   <div class="form-group col-md-2">
				    <label>Doctor Name</label>
				    <p class="input-group">
				     <input type="text"  data-ng-model="bill.doctorId" class="form-control" >									
					 </p>
				  </div>
				   <div class="form-group col-md-2">
				    <label>Generated By</label>
				    <p class="input-group">
				     <input type="text"  data-ng-model="bill.staff" class="form-control" >									
					 </p>
				  </div> -->
			  </div>
                
			  
			  </div>
         <table>
           <thead><tr><th>Medicine Item</th></tr></thead>
           <tbody><tr >
             <td>
             <select class="form-control col-lg-3" ng-options="stock.itemName for stock in masterstock" ng-change="displaySelected()"  ng-model="selectedStock">
                  <!-- <option ng-repeat="stock in masterstock" value="{{stock.itemName}}">
                  	{{stock.itemName}}
                  	</option> -->
                  	
             </select>
             </td>
          
         </tr>
         </tbody>
         </table>
         </div>

<br/>

			<div class="container">
				<div class="row" ng-show="BillItems.length">
				   <div class="col-md-6">
				   		<table class="table table-bordered" style="width: 700px; border:blue;">
				   		    <thead class="thead-inverse">
				   		    <tr>
				   		     <th>Item Id</th> <th>Item</th> <th>Batch Id</th> <th>Expiry data</th> <th>Quantity</th> <th>MRP</th><th>Rate</th><th>Total</th><th>Tax%</th><th>Tax</th>
				   		    </tr>
				   		    </thead>
				   		    <tbody>
				   		       <tr ng-repeat="item in BillItems">
				   		        <td>{{item.medicineId}}</td>
				   		          <td>{{item.itemName}}</td>
				   		           <td>{{item.batchId}}</td>
				   		            <td>{{item.expiryDate | date: 'dd-MM-yyyy'}}</td>
				   		             <td>{{item.quantity}}</td>
				   		              <td>{{item.price}}</td>	
				   		               <td>{{item.rate}}</td>	
				   		               <td>{{item.quantity*item.price}}</td>
				   		                 <td>{{item.taxPercentage}}</td>	
				   		                 <td>{{item.taxAmount}}</td>						   		               
				   		       </tr>
				   		    </tbody>
				   		</table>
				   	
				   		
				   </div>
				</div>
				
				<div class="row" style=" background-color:gray;">
				   <form ng-show="selectedStockItem">
			  		<div class="form-group col-sm-1" >
				    <label>Item Id:</label>
				    <input type="number" class="form-control"  ng-model="selectedStockItem.medicineId"  >
				  </div>

				  <div class="form-group col-sm-2 ">
				    <label>Item Name</label>
				    <input type="text" class="form-control" ng-model="selectedStockItem.itemName">
				   
				  </div>
				  <div class="form-group col-sm-1" >
				    <label>Batch Id:</label>
				    <input type="text"  ng-model="selectedStockItem.batchId" class="form-control" >
				  </div>

				  <div class="form-group col-sm-2 ">
				    <label>Expiry Date</label>
				  <input type="text" class="form-control" ng-model="selectedStockItem.expiryDate" value-date-format format="dd-MM-yyyy">
				   </div>
				   <div class="form-group col-sm-1" >
				    <label>Quantity:</label>
				   <input type="text"  class="form-control" ng-model="selectedStockItem.quantity" integer>
				  </div>
				  <div class="form-group col-sm-1" >
				    <label>MRP:</label>
				    <input type="text"  class="form-control" ng-model="selectedStockItem.price" integer>
				  </div>
				  <div class="form-group col-sm-1" >
				    <label>Discount:</label>
				    <input type="number" class="form-control" ng-model="selectedStockItem.discount">
				  </div>
				    <div class="form-group col-sm-1" >
				    <label>Rate:{{selectedStockItem.quantity*selectedStockItem.price}}</label>
				   <input type="number" class="form-control" ng-model="selectedStockItem.rate " double>
				  </div>
				  <div class="form-group col-sm-1" >
				    <label>Amount:{{selectedStockItem.quantity*selectedStockItem.price}}</label>
				    <input type="number" class="form-control" ng-model="selectedStockItem.amount">
				  </div>
				  <div class="form-group col-sm-1" >
				    <label>Tax %:</label>
				   <input type="number" class="form-control" ng-model="selectedStockItem.taxPercentage">
				  </div>
				  <button type="button" ng-click="addToBillItem()" class="btn btn-default">Submit</button>
				  </form>
			  </div>						
									
				
			</div>
                          <div align="left">
				   			<form >
				   		    <table >
				   		      <tr>
				   		      <td> Total:<input type="number" ng-model="totalAmount"/> 
				   		      		Disc %<input  type="number" ng-model="bill.discountPercent">
				   		      		{{bill.discount_amount}}
				   		      </td>
				   		      </tr>
				   		   <tr>
				   		      <td> Tax % :<input type="number" ng-model="bill.taxPercent" > 
				   		      	 {{bill.tax_amount}}
				   		      	</td>
				   		      </tr>
				   		      <tr>
				   		      <td>
				   		      		Net Total {{netTotalAmount}}
				   		             :<input type="text" ng-model="bill.netTotalAmount" valie="{{$bill.netTotalAmount}}"> 
				   		            
				   		      </td>
				   		      </tr>
				   		      <tr><td><input type="button" style="align:right;" class="btn btn-primary" value="Generate Bill" ng-click="generateBill()" /></td></tr>
				   		   </table>
				   		
				   		</form>
				   		
				   		</div> 

		</div>
</div>
</body>
</html>